echo error

diff --git a/.github/workflows/ansible.yml b/.github/workflows/ansible.yml
--- a/.github/workflows/ansible.yml
+++ b/.github/workflows/ansible.yml
@@ -101,7 +101,7 @@ jobs:
       
       - name: Ensure ansible version is fetched
         if: steps.read-galaxy-yaml.outputs.version == ''
-        run: exit 1
+        run: echo "Cannot read version from galaxy.yml" && exit 1
 
       - name: Push new release tag if it doesn't exist
         uses: actions/github-script@v3
